overwrite: true
schema: '${SALEOR_INSTANCE_URL}'
documents: 'lib/**/*.graphql'
generates:
  lib/saleor/generated/:
    preset: 'client'
    presetConfig:
      fragmentMasking: false
      dedupeFragments: true
    config:
      exportFragmentSpreadSubTypes: true
      defaultScalarType: 'unknown'
      useTypeImports: true
      dedupeFragments: true
      skipTypename: true
      documentMode: 'string'
      scalars:
        _Any: 'unknown'
        Date: 'string'
        DateTime: 'string'
        Decimal: 'number'
        GenericScalar: 'unknown'
        JSON: 'unknown'
        JSONString: 'string'
        Metadata: 'Record<string, string>'
        PositiveDecimal: 'number'
        Upload: 'unknown'
        UUID: 'string'
        WeightScalar: 'number'
    plugins: []
